# Generated by Django 2.2.5 on 2020-03-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100, verbose_name='地址名')),
                ('mobile', models.DateField(max_length=100, verbose_name='电话')),
                ('gender', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=100, verbose_name='地址')),
                ('isDefault', models.IntegerField(default=0, verbose_name='是否默认地址')),
            ],
            options={
                'verbose_name': '地址',
                'verbose_name_plural': '地址',
            },
        ),
        migrations.CreateModel(
            name='Disk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menuId', models.IntegerField(default=0, verbose_name='菜单ID')),
                ('img', models.CharField(max_length=100, verbose_name='图片')),
                ('title', models.CharField(max_length=100, verbose_name='菜名')),
                ('price', models.FloatField(default=0, verbose_name='价格')),
                ('disprice', models.FloatField(default=0, verbose_name='disprice')),
                ('sellpoint', models.CharField(max_length=100, verbose_name='备注')),
                ('created', models.CharField(max_length=100, verbose_name='创建时间')),
                ('updated', models.CharField(max_length=100, verbose_name='更新时间')),
                ('sellnum', models.IntegerField(default=0, verbose_name='分数')),
                ('status', models.IntegerField(default=0, verbose_name='状态')),
            ],
            options={
                'verbose_name': '商户',
                'verbose_name_plural': '商户',
            },
        ),
        migrations.CreateModel(
            name='Evaluate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diskid', models.IntegerField(default=0, verbose_name='商户ID')),
                ('orderid', models.CharField(max_length=100, verbose_name='订单ID')),
                ('openid', models.CharField(max_length=100)),
                ('imgs', models.CharField(max_length=100, verbose_name='用户图片')),
                ('content', models.CharField(max_length=100, verbose_name='评论内容')),
                ('evalValue', models.IntegerField(default=0)),
                ('created', models.DateField(verbose_name='创建时间')),
                ('isAnonymous', models.IntegerField(default=0, verbose_name='')),
                ('nickname', models.CharField(max_length=100, verbose_name='用户名')),
                ('avatarUrl', models.CharField(max_length=100, verbose_name='用户Url')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='菜单名')),
                ('parentId', models.IntegerField(default=0, verbose_name='父菜单ID')),
                ('isParentid', models.IntegerField(default=0, verbose_name='是否为父菜单')),
            ],
            options={
                'verbose_name': '菜单',
                'verbose_name_plural': '菜单',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.CharField(max_length=100, verbose_name='订单ID')),
                ('totalMoney', models.IntegerField(max_length=100, verbose_name='总价格')),
                ('remarks', models.CharField(max_length=100, verbose_name='备注')),
                ('addressid', models.IntegerField(default=0, verbose_name='地址ID')),
                ('diskid', models.IntegerField(default=0, verbose_name='商户ID')),
                ('status', models.CharField(max_length=100, verbose_name='状态')),
                ('num', models.IntegerField(default=0, verbose_name='数量')),
                ('isEvaluate', models.IntegerField(default=0, verbose_name='是否是当前用户')),
            ],
            options={
                'verbose_name': '订单信息',
                'verbose_name_plural': '订单信息',
            },
        ),
        migrations.CreateModel(
            name='OrdersMain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.CharField(max_length=100, verbose_name='订单ID')),
                ('totalMoney', models.IntegerField(max_length=100, verbose_name='总价格')),
                ('remarks', models.CharField(max_length=100, verbose_name='备注')),
                ('status', models.CharField(max_length=100, verbose_name='状态')),
                ('isEvaluate', models.IntegerField(default=0, verbose_name='是否是当前用户')),
                ('createtime', models.DateField(verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='食堂名')),
                ('address', models.CharField(max_length=100, verbose_name='地址')),
                ('time', models.DateField(max_length=100, verbose_name='创建时间')),
                ('phone', models.CharField(max_length=100, verbose_name='手机号')),
            ],
            options={
                'verbose_name': '购物',
                'verbose_name_plural': '购物',
            },
        ),
    ]
