# Generated by Django 2.2.5 on 2020-03-15 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disk',
            old_name='sellpoint',
            new_name='sellPoint',
        ),
        migrations.RemoveField(
            model_name='disk',
            name='disprice',
        ),
        migrations.AddField(
            model_name='disk',
            name='disPrice',
            field=models.FloatField(default=0, verbose_name='disprice'),
        ),
    ]
